---
# Tasks to setup Nexus the first time

# If the admin password is defined and set we need to set it
# later in this playbook
- name: Set new admin password if admin password is defined
  when:
  - _nexus_admin_password is defined
  - _nexus_admin_password | length > 0
  set_fact:
    _nexus_new_admin_password: "{{ _nexus_admin_password }}"

# Discover admin password for 3.17+
- name: Get name of nexus pod
  k8s_facts:
    api_version: v1
    kind: Pod
    namespace: "{{ _nexus_namespace }}"
    label_selectors: "app={{ _nexus_name }}"
  register: r_nexus_pod

- name: Attempt to fetch password file
  shell: "oc cp {{ r_nexus_pod.resources[0].metadata.name }}:/nexus-data/admin.password /tmp/admin.password -n {{ _nexus_namespace }}"
  ignore_errors: true

- name: Check for temporary file
  stat:
    path: /tmp/admin.password
  register: password_file_result

- name: Get Admin Password for 3.17+
  when: password_file_result.stat.exists
  block:
  - name: Read file
    slurp:
      src: /tmp/admin.password
    register: r_admin_password
  - name: Save admin password
    set_fact:
      _nexus_admin_password: "{{ r_admin_password['content']|b64decode }}"
  - name: Remove temporary file
    file:
      path: /tmp/admin.password
      state: absent

# Upload all groovy scripts we will be using
- name: Declare groovy scripts
  include_tasks: declare_script.yml
  with_items:
    - update_admin_password
    - delete_repo
    - create_repo_maven_proxy
    - create_repo_maven_group
    - create_repo_maven_hosted
    - create_repo_docker_hosted
    - create_repo_npm_hosted
    - create_repo_npm_proxy
    - create_repo_npm_group
    - set_anon_access

# Delete default repos
- name: Delete default repos
  include_tasks: delete_repo.yml
  when: _nexus_delete_default_repos | bool
  with_items:
    - maven-central
    - maven-public
    - maven-releases
    - maven-snapshots
    - nuget-group
    - nuget-hosted
    - nuget.org-proxy

- name: Create Maven Proxies
  include_tasks: create_repo_maven_proxy.yml
  with_items: "{{ nexus_repos_maven_proxy | d(_nexus_repos_maven_proxy) }}"

- name: Create Maven Hosted Repos
  include_tasks: create_repo_maven_hosted.yml
  with_items: "{{ nexus_repos_maven_hosted | d(_nexus_repos_maven_hosted) }}"

- name: Create Maven Groups
  include_tasks: create_repo_maven_group.yml
  with_items: "{{ nexus_repos_maven_group |  d(_nexus_repos_maven_group) }}"

- name: Create Docker Repos
  include_tasks: create_repo_docker_hosted.yml
  with_items: "{{ nexus_repos_docker_hosted | d(_nexus_repos_docker_hosted) }}"

- name: Create NPM Proxies
  include_tasks: create_repo_npm_proxy.yml
  with_items: "{{ nexus_repos_npm_proxy | d(_nexus_repos_npm_proxy) }}"

- name: Create NPM Groups
  include_tasks: create_repo_npm_group.yml
  with_items: "{{ nexus_repos_npm_group | d(_nexus_repos_npm_group) }}"

- name: Turn on Anonymous Access
  include_tasks: set_anon_access.yml

- name: Update Admin Password
  when: _nexus_new_admin_password is defined
  include_tasks: update_admin_password.yml

- name: Change default password
  when: _nexus_new_admin_password is defined
  set_fact:
    _nexus_admin_password: "{{ _nexus_new_admin_password }}"

# The following will fail unless this is running as an operator
# Report current admin password in Nexus CR status
- name: Save password in custom resource status
  k8s_status:
    api_version: gpte.opentlc.com/v1alpha1
    kind: Nexus
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    status:
      admin_password: "{{ _nexus_admin_password }}"
  ignore_errors: true
